---
- name: Install apt dependencies
  apt:
    name:
      - openssl
      - python-pip
      - python-setuptools

- name: Install pip dependencies
  pip:
    name: docker

- name: Create Nginx dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ nginx_dir }}"
    - "{{ nginx_conf_dir }}"
    - "{{ nginx_conf_dir }}/ssl"

- name: Create Let's Encrypt dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ lets_encrypt_dir }}"
    - "{{ lets_encrypt_dir }}/logs"
    - "{{ lets_encrypt_web_root }}"

- name: Deploy nginx ssl options
  template:
    src: nginx/options-ssl-nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/ssl/options-ssl-nginx.conf"
    mode: 0644

- name: Generate Diffie-Hellman (DH) key exchange
  command: openssl dhparam -out {{ nginx_conf_dir }}/ssl/dhparam.pem 2048
  args:
    creates: "{{ nginx_conf_dir }}/ssl/dhparam.pem"

- name: Deploy backends templates
  template:
    src: nginx/backend.com.conf.j2
    dest: "{{ nginx_conf_dir }}/{{ item.name }}.conf"
    mode: 0644
  with_items: "{{ backends }}"
  notify: nginx reload

- name: Run docker nginx image
  docker_container:
    name: "{{ docker_name }}"
    state: started
    image: "{{ docker_image }}"
    restart_policy: always
    volumes:
      - "{{ lets_encrypt_dir }}:/etc/letsencrypt"
      - "{{ lets_encrypt_web_root }}:/var/www/letsencrypt"
      - "{{ nginx_conf_dir }}/ssl:/etc/nginx/conf.d/ssl"
      - "{{ nginx_conf_dir }}/oscaresteve.com.conf:/etc/nginx/conf.d/oscaresteve.com.conf"
    published_ports:
      - "80:80"
      - "443:443"

- include_tasks: generate_certs.yml
  with_items: "{{ backends }}"
  when: generate_certs
